service: image-sharer

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

functions:
  me:
    handler: handler.me
    events:
      - http:
          path: me/{id}
          method: get
          request:
            parameters:
              paths:
                id: true